### ISSUE TITLE
3 errors in compute.compute_cwave_parameters

### ISSUE THREAD

**Issue by lanougue** [umr-lops/utils_xsarslc_l1b#48]
1 - In
`xxsmn = xxsm / xxsm.sum(dim=['k_rg', 'k_az']) * dkx * dky`
dkx and dky should be in the denominator

2 - In
`cwave_parameters = ((kernel.cwave_kernel * xxsmn) * dky * dky).sum(dim=['k_rg', 'k_az']).rename('cwave_params').to_dataset()`
it should be `dkx*dky`

3 - In
`cwave_parameters = ((kernel.cwave_kernel * xxsmn) * dky * dky).sum(dim=['k_rg', 'k_az']).rename('cwave_params').to_dataset()`
to_dataset() can be removed since there is only one DataArray inside

**Comment by agrouaze** [comment]
fixed by #50
